GET http://localhost:4004/odata/v4/library-srv

###
GET http://localhost:4004/odata/v4/library-srv/BooksSet

###
GET http://localhost:4004/odata/v4/library-srv/BooksSet(751eb8c8-26af-4e0a-9b56-7a0adb4994a5)

###
Post http://localhost:4004/odata/v4/library-srv/BooksSet
Content-Type: application/json

{
    "title":"Refactoring",
    "author":"Martin Fowler",
    "price": 49.99,
    "publishedDate":"2024-06-01T00:00:00Z",
    "digitalCopy": true
}

###
PUT http://localhost:4004/odata/v4/library-srv/BooksSet(751eb8c8-26af-4e0a-9b56-7a0adb4994a5)
Content-Type: application/json

{
     "title":"Refactoring232323g4",
    "author":"Martin Fowler99",
    "price": 47,
    "publishedDate":"2024-06-01T00:00:00Z",
    "digitalCopy": false
}

###
DELETE http://localhost:4004/odata/v4/library-srv/BooksSet(751eb8c8-26af-4e0a-9b56-7a0adb4994a5)